import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument, Schema as MongooseSchema, Types } from 'mongoose';
import { User } from '../../users/schemas/user.schema';
import {
  RECURRENCE_FREQUENCIES,
  TASK_CATEGORIES,
  TASK_PRIORITIES,
  TOMBSTONE_RETENTION_DAYS,
  type RecurrenceFrequency,
  type TaskCategory,
  type TaskPriority,
} from '../task.constants';

/**
 * How a task repeats. The time of day, weekday, day of the month and so on
 * come from the task's `scheduledAt` as seen in its `timeZone`, so "9:00 every
 * day" stays 9:00 across daylight saving changes.
 */
@Schema({ _id: false })
export class Recurrence {
  @Prop({ type: String, enum: RECURRENCE_FREQUENCIES, required: true })
  freq: RecurrenceFrequency;

  /** Every `interval` hours, days, weeks... (1 = every one). */
  @Prop({ required: true, min: 1, max: 999 })
  interval: number;

  /** Weekly only: the days it repeats on, 0 = Sunday ... 6 = Saturday. Empty = scheduledAt's day. */
  @Prop({ type: [Number], default: [] })
  byWeekday: number[];

  /**
   * Monthly and yearly: the day of the month, 1-31, kept separately because
   * scheduledAt moves to a shorter month's last day (31 → 30 April). Null =
   * scheduledAt's day.
   */
  @Prop({ type: Number, default: null, min: 1, max: 31 })
  byMonthDay: number | null;
}
const RecurrenceSchema = SchemaFactory.createForClass(Recurrence);

@Schema({ timestamps: true })
export class Task {
  /** Owner — every query is scoped by this field so users only see their own tasks. */
  @Prop({ type: MongooseSchema.Types.ObjectId, ref: User.name, required: true, index: true })
  owner: Types.ObjectId;

  /**
   * The task's ID in sync: generated by the app (a UUID) so a task can be
   * created offline. Tasks created through the REST API, or before sync
   * existed, use their `_id` as hex. The REST API keeps addressing tasks by
   * `_id`, which older app versions use.
   */
  @Prop({ required: true })
  uid: string;

  @Prop({ required: true, trim: true, maxlength: 120 })
  title: string;

  @Prop({ trim: true, maxlength: 1000, default: '' })
  description: string;

  /** When the user plans to work on the task ("date-time"). */
  @Prop({ required: true })
  scheduledAt: Date;

  /** Hard due date. Optional — not every task has one. */
  @Prop({ type: Date, default: null })
  deadline: Date | null;

  @Prop({ type: String, enum: TASK_PRIORITIES, default: 'medium' })
  priority: TaskPriority;

  @Prop({ type: String, enum: TASK_CATEGORIES, default: 'personal' })
  category: TaskCategory;

  /** Free-form labels, normalised to lowercase. */
  @Prop({ type: [String], default: [] })
  tags: string[];

  @Prop({ default: false })
  completed: boolean;

  @Prop({ type: Date, default: null })
  completedAt: Date | null;

  /** Remind this many minutes before `scheduledAt` (0 = at that time); null = no reminder. */
  @Prop({ type: Number, default: null })
  reminderOffset: number | null;

  /** Null for a one-off task. */
  @Prop({ type: RecurrenceSchema, default: null })
  recurrence: Recurrence | null;

  /** IANA time zone the task was planned in, e.g. Asia/Kolkata. */
  @Prop({ type: String, default: null })
  timeZone: string | null;

  /**
   * When the task was last changed, by the clock of the device that changed
   * it. Sync keeps the version with the latest one (last write wins).
   */
  @Prop({ type: Date, default: () => new Date() })
  clientUpdatedAt: Date;

  /**
   * When the server last stored a change, by its own clock. Devices pull
   * everything changed since their last sync by this, never by device
   * clocks, which can disagree.
   */
  @Prop({ type: Date, default: () => new Date() })
  serverUpdatedAt: Date;

  /**
   * Deleted tasks stay for a while as tombstones so every device learns
   * about the deletion, then a TTL index removes them.
   */
  @Prop({ type: Date, default: null })
  deletedAt: Date | null;

  createdAt: Date;
  updatedAt: Date;
}

export type TaskDocument = HydratedDocument<Task>;
export const TaskSchema = SchemaFactory.createForClass(Task);

// New tasks from the REST API get their _id as sync ID.
TaskSchema.pre('validate', function (next) {
  if (!this.uid) this.uid = this._id.toHexString();
  next();
});

// Supports the common "my open tasks by deadline" access pattern.
TaskSchema.index({ owner: 1, completed: 1, deadline: 1 });
// One task per sync ID and owner. Partial, so documents from before sync
// (no uid until TasksService backfills it) don't collide while the index builds.
TaskSchema.index(
  { owner: 1, uid: 1 },
  { unique: true, partialFilterExpression: { uid: { $type: 'string' } } },
);
// Sync pulls: "this owner's changes after the cursor", in cursor order.
TaskSchema.index({ owner: 1, serverUpdatedAt: 1, uid: 1 });
// Tombstones expire. Live tasks have deletedAt null, which TTL ignores.
TaskSchema.index({ deletedAt: 1 }, { expireAfterSeconds: TOMBSTONE_RETENTION_DAYS * 24 * 60 * 60 });
